# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CU Student Hub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CU Student Hub
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  
end
