//
//  Subject.swift
//  CU Student Hub
//
//  Created by Anthony Yang on 5/4/19.
//  Copyright © 2019 Anthony Yang. All rights reserved.
//

import Foundation

enum Subject {
    case AAS, AEM, AEP, AGSCI, AIIS, AIRS, ALS, AMST, ANSC, ANTHR, ARAB, ARCH, ARKEO, ART, ARTH, AS, ASIAN, ASL, ASRC, ASTRO, BCS, BEE, BENGL, BIOAP, BIOEE, BIOG, BIOMG, BIOMI, BIOMS, BIONB, BME, BPRE, BSOC, BTRY, BURM, CAPS, CEE, CHEM, CHEME, CHIN, CHLIT, CLASS, COGST, COLLS, COML, COMM, CRP, CS, CZECH, DEA, DSOC, DUTCH, EAS, ECE, ECON, EDUC, ELSO, ENGL, ENGRC, ENGRD, ENGRG, ENGRI, ENMGT, ENTOM, ESS, FDSC, FGSS, FINN, FREN, FSAD, GERST, GOVT, GRAD, GREEK, HADM, HD, HE, HEBRW, HINDI, HIST, HUNGR, IARD, ILRHR, ILRIC, ILRID, ILRLE, ILRLR, ILROB, ILRST, IM, INDO, INFO, ITAL, JAPAN, JPLIT, JWST, KHMER, KOREA, LA, LATA, LATIN, LAW, LEAD, LGBT, LING, LSP, MAE, MATH, MEDVL, MGMT, MILS, MSE, MUSIC, NACCT, NAVS, NBA, NBAT, NBAY, NCC, NCCY, NEPAL, NES, NMI, NRE, NS, NSE, NTRES, ORIE, PADM, PALI, PAM, PE, PERSN, PHIL, PHYS, PLBIO, PLBRG, PLHRT, PLPPM, PLSCI, PLSCS, PMA, POLSH, PORT, PSYCH, PUNJB, RELST, ROMAN, ROMS, RUSSA, RUSSL, SANSK, SHUM, SINHA, SNLIT, SOC, SPAN, STS, STSCI, SUMER, SWAHL, SYSEN, TAG, TAMIL, TECH, THAI, TIBET, TOX, TURK, UKRAN, URDU, VETCS, VETMI, VETMM, VIEN, VIET, VISST, VTBMS, VTMED, VTPMD, WOLOF, WRIT, YORUB, ZULU
}

struct AllSubject {
    static let array : [Subject] = [.AAS, .AEM, .AEP, .AGSCI, .AIIS, .AIRS, .ALS, .AMST, .ANSC, .ANTHR, .ARAB, .ARCH, .ARKEO, .ART, .ARTH, .AS, .ASIAN, .ASL, .ASRC, .ASTRO, .BCS, .BEE, .BENGL, .BIOAP, .BIOEE, .BIOG, .BIOMG, .BIOMI, .BIOMS, .BIONB, .BME, .BPRE, .BSOC, .BTRY, .BURM, .CAPS, .CEE, .CHEM, .CHEME, .CHIN, .CHLIT, .CLASS, .COGST, .COLLS, .COML, .COMM, .CRP, .CS, .CZECH, .DEA, .DSOC, .DUTCH, .EAS, .ECE, .ECON, .EDUC, .ELSO, .ENGL, .ENGRC, .ENGRD, .ENGRG, .ENGRI, .ENMGT, .ENTOM, .ESS, .FDSC, .FGSS, .FINN, .FREN, .FSAD, .GERST, .GOVT, .GRAD, .GREEK, .HADM, .HD, .HE, .HEBRW, .HINDI, .HIST, .HUNGR, .IARD, .ILRHR, .ILRIC, .ILRID, .ILRLE, .ILRLR, .ILROB, .ILRST, .IM, .INDO, .INFO, .ITAL, .JAPAN, .JPLIT, .JWST, .KHMER, .KOREA, .LA, .LATA, .LATIN, .LAW, .LEAD, .LGBT, .LING, .LSP, .MAE, .MATH, .MEDVL, .MGMT, .MILS, .MSE, .MUSIC, .NACCT, .NAVS, .NBA, .NBAT, .NBAY, .NCC, .NCCY, .NEPAL, .NES, .NMI, .NRE, .NS, .NSE, .NTRES, .ORIE, .PADM, .PALI, .PAM, .PE, .PERSN, .PHIL, .PHYS, .PLBIO, .PLBRG, .PLHRT, .PLPPM, .PLSCI, .PLSCS, .PMA, .POLSH, .PORT, .PSYCH, .PUNJB, .RELST, .ROMAN, .ROMS, .RUSSA, .RUSSL, .SANSK, .SHUM, .SINHA, .SNLIT, .SOC, .SPAN, .STS, .STSCI, .SUMER, .SWAHL, .SYSEN, .TAG, .TAMIL, .TECH, .THAI, .TIBET, .TOX, .TURK, .UKRAN, .URDU, .VETCS, .VETMI, .VETMM, .VIEN, .VIET, .VISST, .VTBMS, .VTMED, .VTPMD, .WOLOF, .WRIT, .YORUB, .ZULU]
}
